// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { perplexityBlock } from ".";
import { auth } from "./auth";

export const perplexityBlockSchema = parseBlockSchema(perplexityBlock);
export const perplexityCredentialsSchema = parseBlockCredentials(
  perplexityBlock.id,
  auth.schema,
);
